[package]
name = "bevy_stdin"
version = "0.2.0"
edition = "2024"
description = "Receive input from stdin"
license = "MIT OR Apache-2.0"
repository = "https://github.com/scurvydoggo/bevy_stdin"
keywords = ["bevy"]

[dependencies]
bevy = "0.16.1"
crossbeam-channel = "0.5.15"
crossterm = "0.29.0"
